[package]
name = "editor-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
editor-core = { path = "../editor-core" }
eframe = "0.29"
egui = "0.29"
